# 服务器端口
system:
  port: :8202
  status: debug
# log存放目录
logger:
  path: ./logs/r0Website_server.log
# jwt配置
jwt:
  sign-key: Crayfishr08202 # !密码
  expires-time: 3000
  issuer: r0
# mongo配置
mongo:
  address: 101.33.218.37 # 与docker-net网关或者服务器ip相同
  part: 27017
  db: r0website_server
  super-admin-name: readWriteR0
  super-admin-pswd: cherilee233mongo
# author配置
author:
  name: r0
  email: boogieling_O@qq.com
# docker自定义网络的配置
docker:
  subnet: 172.97.0.0/16 # docker-net 子网号
  gateway: 172.97.0.1 # docker-net 网关